# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YVLeadrboard' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YVLeadrboard
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'GooglePlaces'
  pod 'GoogleMaps'

end
